#!/usr/bin/env bash

#set -x
set -e
set -o pipefail

bin=$(cd $(dirname "$0") > /dev/null; pwd)

setup_config() {
  ln -sf $bin/config $HOME/.ssh/config
}

setup_github_keys() {
  if [ ! -e $HOME/.ssh/github ]; then
    ssh-keygen -t rsa  -f $HOME/.ssh/github -N ''
  fi
}

main() {
  if [ ! -d "$HOME/.ssh" ]; then
    mkdir "$HOME/.ssh"
    chmod 700 "$HOME/.ssh"
  fi
  setup_config
  setup_github_keys
}

main "$@"
