#!/usr/bin/env bash

set -e
set -o pipefail

bin=`dirname "$0"`
bin=`cd "$bin">/dev/null; pwd`

git_plugins=(
  "https://github.com/tpope/vim-sensible.git"
  "https://github.com/kien/rainbow_parentheses.vim.git"
  "https://github.com/guns/vim-clojure-static.git"
  "https://github.com/guns/vim-clojure-highlight.git"
  "https://github.com/tpope/vim-fireplace.git"
  "https://github.com/scrooloose/nerdtree.git"
  "https://github.com/elzr/vim-json.git"
  "https://github.com/altercation/vim-colors-solarized.git"
  "https://github.com/tfnico/vim-gradle.git"
  "https://github.com/othree/xml.vim.git"
  "https://github.com/derekwyatt/vim-scala.git"
  "https://github.com/lambdatoast/elm.vim.git"
)

git_name() {
  basename "$1" | sed 's;.git;;g'
}

git_install() {
  local url="$1"
  local name=$(git_name "$url")

  cd ~/.vim/bundle
  if [ -d "$name" ]; then
    cd "$name"
    git pull
  else
    git clone "$1"
  fi
}

main() {
  # setup vim-pathogen and install the plugins through that
  mkdir -p ~/.vim/autoload ~/.vim/bundle
  if [ ! -e ~/.vim/autoload/pathogen.vim ]; then
    wget --no-check-certificate -O ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
  fi

  for plugin in "${git_plugins[@]}"; do
    git_install "$plugin"
  done
}

main "$@"
