#!/usr/bin/env bash

set -e
set -o pipefail

bin=$(cd $(dirname "$0"); pwd)

# to force the colors to show up
source $bin/../bash/*-colors.bash

for installer in $(find "$bin/.." -name "*.install" | perl -e "print sort{(split '/', \$a)[-1] <=> (split '/', \$b)[-1]}<>")
do
  echo -e "${txtblu}Setting up ${txtred}${installer}${txtrst}...${txtrst}"
  bash -c "$installer"
done
